package com.infotech.skills.hbm.piaprofile;
// Generated Aug 17, 2013 1:17:46 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

import com.infotech.skills.master.MasterVO;

/**
 * PiaActivity generated by hbm2java
 */
public class ActivityVO  extends MasterVO implements Serializable {

     private String activityId;
     private String activityName;
     private String activityShortName;

    public ActivityVO() {
    }

	
    public ActivityVO(String activityId, String activityName) {
        this.activityId = activityId;
        this.activityName = activityName;
    }
    public ActivityVO(String activityId, String activityName, String activityShortName) {
       this.activityId = activityId;
       this.activityName = activityName;
       this.activityShortName = activityShortName;
    }
   
    public String getActivityId() {
        return this.activityId;
    }   
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }
    public String getActivityName() {
        return this.activityName;
    }  
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }
    public String getActivityShortName() {
        return this.activityShortName;
    }   
    public void setActivityShortName(String activityShortName) {
        this.activityShortName = activityShortName;
    }  

}
