package com.infotech.skills.hbm.admin;
// Generated Aug 19, 2013 5:52:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MstAssignRole generated by hbm2java
 */
public class AssignRoleVO  implements java.io.Serializable {
	
	 private String loginId;
     private String roleCd;
     private String entityCode;;
     private String levelCd;
     private String levelRole;
     private String createdOn;
     private String createdBy;
     private String modifiedBy;
     private String modifiedOn;

    
    public String getLevelCd() {
        return this.levelCd;
    }
    public void setLevelCd(String levelCd) {
        this.levelCd = levelCd;
    }
    public String getLevelRole() {
        return this.levelRole;
    }
    
    public void setLevelRole(String levelRole) {
        this.levelRole = levelRole;
    }
    
    public String getCreatedBy() {
        return this.createdBy;
    }   
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }   
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getRoleCd() {
		return roleCd;
	}
	public void setRoleCd(String roleCd) {
		this.roleCd = roleCd;
	}
	public String getEntityCode() {
		return entityCode;
	}
	public void setEntityCode(String entityCode) {
		this.entityCode = entityCode;
	}
	public String getCreatedOn() {
		return createdOn;
	}
	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}
	public String getModifiedOn() {
		return modifiedOn;
	}
	public void setModifiedOn(String modifiedOn) {
		this.modifiedOn = modifiedOn;
	}
   

}


