package com.infotech.skills.hbm.admin;
// Generated Aug 17, 2013 3:38:17 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MstFormModule generated by hbm2java
 */
public class MstFormModule  implements java.io.Serializable {


     private String formCd;
     private MstFormModule mstFormModule;
     private String formName;
     private String moduleCd;
     private String url;
     private String createdBy;
     private Date createdOn;
     private String lastModifiedBy;
     private Date lastModifiedOn;
     private BigDecimal order;
     private Set<MstFormModule> mstFormModules = new HashSet<MstFormModule>(0);

    public MstFormModule() {
    }

	
    public MstFormModule(String formCd, MstFormModule mstFormModule) {
        this.formCd = formCd;
        this.mstFormModule = mstFormModule;
    }
  
    public String getFormCd() {
        return this.formCd;
    }
    
    public void setFormCd(String formCd) {
        this.formCd = formCd;
    }
    public MstFormModule getMstFormModule() {
        return this.mstFormModule;
    }
    
    public void setMstFormModule(MstFormModule mstFormModule) {
        this.mstFormModule = mstFormModule;
    }
    public String getFormName() {
        return this.formName;
    }
    
    public void setFormName(String formName) {
        this.formName = formName;
    }
    public String getModuleCd() {
        return this.moduleCd;
    }
    
    public void setModuleCd(String moduleCd) {
        this.moduleCd = moduleCd;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public Date getLastModifiedOn() {
        return this.lastModifiedOn;
    }
    
    public void setLastModifiedOn(Date lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
    }
    public BigDecimal getOrder() {
        return this.order;
    }
    
    public void setOrder(BigDecimal order) {
        this.order = order;
    }
    public Set<MstFormModule> getMstFormModules() {
        return this.mstFormModules;
    }
    
    public void setMstFormModules(Set<MstFormModule> mstFormModules) {
        this.mstFormModules = mstFormModules;
    }


}


