package com.infotech.skills.hbm.admin;
// Generated Aug 17, 2013 3:38:17 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MstRole generated by hbm2java
 */
public class MstRole  implements java.io.Serializable {


     private String roleCd;
     private String roleName;
     private String roleDesc;
     private String levelCd;
     private String createdBy;
     private Date createdOn;
     private String lastModifiedBy;
     private Date lastModifiedOn;
     private String schemeCode;

    public MstRole() {
    }

	
    public MstRole(String roleCd) {
        this.roleCd = roleCd;
    }
    public MstRole(String roleCd, String roleName, String roleDesc, String levelCd, String createdBy, Date createdOn, String lastModifiedBy, Date lastModifiedOn, String schemeCode) {
       this.roleCd = roleCd;
       this.roleName = roleName;
       this.roleDesc = roleDesc;
       this.levelCd = levelCd;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.lastModifiedBy = lastModifiedBy;
       this.lastModifiedOn = lastModifiedOn;
       this.schemeCode = schemeCode;
    }
   
    public String getRoleCd() {
        return this.roleCd;
    }
    
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleDesc() {
        return this.roleDesc;
    }
    
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }
    public String getLevelCd() {
        return this.levelCd;
    }
    
    public void setLevelCd(String levelCd) {
        this.levelCd = levelCd;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public Date getLastModifiedOn() {
        return this.lastModifiedOn;
    }
    
    public void setLastModifiedOn(Date lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
    }
    public String getSchemeCode() {
        return this.schemeCode;
    }
    
    public void setSchemeCode(String schemeCode) {
        this.schemeCode = schemeCode;
    }




}


