package com.infotech.skills.hbm.admin;
// Generated Aug 17, 2013 3:38:17 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.infotech.skills.master.MasterVO;

/**
 * MstUser generated by hbm2java
 */
public class UserVO  extends MasterVO implements Serializable {

     private String userCd;
     private String userName;
     private String levelCd;
     private String userDesign;
     private String loginId;
     private String password;
     private String emailId;
     private String activeFlag;  
     private String entityCode;
     private int loginAttempt;
     private String loginStatus;
     private String mobile;

    public String getUserCd() {
        return this.userCd;
    }
    
    public void setUserCd(String userCd) {
        this.userCd = userCd;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getLevelCd() {
        return this.levelCd;
    }
    
    public void setLevelCd(String levelCd) {
        this.levelCd = levelCd;
    }
    public String getUserDesign() {
        return this.userDesign;
    }
    
    public void setUserDesign(String userDesign) {
        this.userDesign = userDesign;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    
    public String getActiveFlag() {
        return this.activeFlag;
    }   
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }
    
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    public int getLoginAttempt() {
		return loginAttempt;
	}
	public void setLoginAttempt(int loginAttempt) {
		this.loginAttempt = loginAttempt;
	}
	public String getLoginStatus() {
        return this.loginStatus;
    }   
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }
    public String getMobile() {
        return this.mobile;
    }
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


